spring:
  datasource:
    url: jdbc:mysql://183.99.247.17:12787/saveme_comparator
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8881
  ssl:
    enabled: true
    key-store: /root/test/isu.jks
    key-store-password: 123456
    key-password: 123456
    key-alias: isu
    trust-store: /root/test/isu.ts
    trust-store-password: 123456